# Generated by Django 4.2.1 on 2023-05-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="username",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
